set(input "${INPUT}")
set(output "${OUTPUT}")
file(READ "${input}" content)
string(REPLACE "\r\n" "\n" content "${content}")
string(REPLACE "\n" ";" content "${content}")
set(lines ${content})
set(filtered "")
foreach(line IN LISTS lines)
	if(line MATCHES "^prefer" OR line MATCHES "^optional plugin" OR line MATCHES "^linktarget" OR line MATCHES "^classname")
		# skip plugin directives
	else()
		list(APPEND filtered "${line}")
	endif()
endforeach()
string(REPLACE ";" "\n" content "${filtered}")
if(NOT content STREQUAL "")
	set(content "${content}\n")
endif()
string(REPLACE "\n" "\r\n" content "${content}")
get_filename_component(output_dir "${output}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(WRITE "${output}" "${content}")
